name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      force:
        description: "Enter 'force' if you want to force a refresh"
        required: false
        default: ""

jobs:
  continuous-integration:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Application and Run unit Test
        run: python run.py & pytest

  continuous-deployment:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: write
      
    url: "http://44.197.177.204"
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Create CodeDeploy Deployment
        id: deploy
        # Assuming the Deployment Group is already setup
        run: |
          aws deploy create-deployment \
            --application-name MySite \
            --deployment-group-name MySite \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}